import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Spinner } from 'react-bootstrap';
import { ButtonWithWallet } from '../../wallets/ButtonWithWallet';
import { ScrollAnchor } from '../../components/ScrollAnchor';
import { LightningHyperlinkModal } from '../components/LightningHyperlinkModal';
import { SwapExpiryProgressBar } from '../components/SwapExpiryProgressBar';
import { SwapForGasAlert } from '../components/SwapForGasAlert';
import { StepByStep } from '../../components/StepByStep';
import { LightningQR } from '../components/LightningQR';
import { BaseButton } from '../../components/BaseButton';
import { SwapStepAlert } from '../components/SwapStepAlert';
import { ic_check_circle } from 'react-icons-kit/md/ic_check_circle';
import { ic_warning } from 'react-icons-kit/md/ic_warning';
import { useFromBtcLnQuote2 } from './useFromBtcLnQuote2';
/*
Steps:
1. Awaiting lightning payment -> Lightning payment received
2. Send commit transaction -> Sending commit transaction -> Commit transaction confirmed
3. Send claim transaction -> Sending claim transaction -> Claim success
 */
export function FromBTCLNQuoteSummary2(props) {
    const page = useFromBtcLnQuote2(props.quote, props.setAmountLock);
    const isInitiated = !page.step1init;
    return (_jsxs(_Fragment, { children: [isInitiated ? (_jsxs("div", { className: "swap-panel__card", children: [page.executionSteps ? (_jsx(StepByStep, { quote: props.quote, steps: page.executionSteps })) : null, _jsx(SwapStepAlert, { show: !!page.step1init?.error, type: "error", icon: ic_warning, title: page.step1init?.error?.title, description: page.step1init?.error?.error.message, error: page.step1init?.error?.error }), page.step2paymentWait?.walletDisconnected ? (_jsxs(_Fragment, { children: [_jsx(LightningQR, { quote: props.quote, setAutoClaim: page.step2paymentWait.walletDisconnected.autoClaim.onChange, autoClaim: page.step2paymentWait.walletDisconnected.autoClaim.value, onHyperlink: page.step2paymentWait.walletDisconnected.payWithLnWallet.onClick }), _jsx("div", { className: "swap-panel__card__group", children: _jsx(SwapExpiryProgressBar, { timeRemaining: page.step2paymentWait.expiry.remaining, totalTime: page.step2paymentWait.expiry.total, show: true, type: "bar", expiryText: "Swap address expired, please do not send any funds!", quoteAlias: "Lightning invoice" }) })] })) : null, _jsx(SwapStepAlert, { show: !!page.step3claim?.error, type: "error", icon: ic_warning, title: page.step3claim?.error?.title, description: page.step3claim?.error?.error.message, error: page.step3claim?.error?.error }), _jsx(SwapStepAlert, { show: page.step4?.state === 'success', type: "success", icon: ic_check_circle, title: "Swap success", description: "Your swap was executed successfully!" }), _jsx(SwapStepAlert, { show: page.step4?.state === 'failed', type: "danger", icon: ic_warning, title: "Swap failed", description: "Swap HTLC expired, your lightning payment will be refunded shortly!" })] })) : null, page.step1init ? (page.step1init.invalidSmartChainWallet ? (_jsx(ButtonWithWallet, { chainId: props.quote.chainIdentifier, requiredWalletAddress: props.quote._getInitiator(), size: "lg", className: "swap-panel__action" })) : (_jsxs(_Fragment, { children: [_jsx(SwapForGasAlert, { notEnoughForGas: page.step1init.additionalGasRequired?.rawAmount, quote: props.quote }), _jsx(ButtonWithWallet, { requiredWalletAddress: props.quote._getInitiator(), chainId: props.quote?.chainIdentifier, className: "swap-panel__action", onClick: page.step1init.init, disabled: !!props.notEnoughForGas, size: "lg", children: "Swap" })] }))) : null, page.step2paymentWait ? (_jsxs(_Fragment, { children: [_jsx(LightningHyperlinkModal, { opened: !!page.step2paymentWait.walletDisconnected?.addressComeBackWarningModal, close: page.step2paymentWait.walletDisconnected?.addressComeBackWarningModal?.close, setShowHyperlinkWarning: page.step2paymentWait.walletDisconnected?.addressComeBackWarningModal?.showAgain
                            .onChange }), _jsx(BaseButton, { onClick: props.abortSwap, variant: "danger", className: "swap-panel__action is-large", children: "Abort swap" })] })) : null, page.step3claim ? (_jsxs(_Fragment, { children: [_jsxs(ButtonWithWallet, { requiredWalletAddress: props.quote._getInitiator(), className: "swap-panel__action", chainId: props.quote?.chainIdentifier, onClick: page.step3claim.commit.onClick, disabled: page.step3claim.commit.disabled, size: page.step3claim.commit.size, children: [page.step3claim.commit.loading ? (_jsx(Spinner, { animation: "border", size: "sm", className: "mr-2" })) : (''), page.step3claim.commit.text] }), page.step3claim.claim ? (_jsxs(ButtonWithWallet, { requiredWalletAddress: props.quote._getInitiator(), chainId: props.quote?.chainIdentifier, onClick: page.step3claim.claim.onClick, disabled: page.step3claim.claim.disabled, size: page.step3claim.claim.size, className: "swap-panel__action", children: [page.step3claim.claim.loading ? (_jsx(Spinner, { animation: "border", size: "sm", className: "mr-2" })) : (''), page.step3claim.claim.text] })) : null] })) : null, page.step4 ? (_jsx(BaseButton, { onClick: props.refreshQuote, variant: "primary", className: "swap-panel__action", children: "New quote" })) : null, _jsx(ScrollAnchor, { trigger: page.step1init == null })] }));
}
