import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Accordion, Badge, OverlayTrigger, Tooltip } from 'react-bootstrap';
import { TokenIcon } from '../tokens/TokenIcon';
import { SwapExpiryProgressCircle } from "../swaps/SwapExpiryProgressCircle";
import { FEConstants } from "../../FEConstants";
function FeePart(props) {
    return (_jsxs("div", { className: 'd-flex font-medium ' + props.className, children: [_jsxs("small", { className: "d-flex align-items-center", children: [props.description == null ? (props.text) : (_jsx(OverlayTrigger, { overlay: _jsx(Tooltip, { id: 'fee-tooltip-desc-' + props.text, children: _jsx("span", { children: props.description }) }), children: _jsx("span", { className: "dottedUnderline", children: props.text }) })), props.composition == null ? ('') : (_jsx(OverlayTrigger, { overlay: _jsx(Tooltip, { id: 'fee-tooltip-' + props.text, children: _jsxs("span", { children: [(Math.round(props.composition.percentage.percentage * 10) / 10).toFixed(1), "% +", ' ', props.composition.base.amount, " ", props.composition.base.token.ticker] }) }), children: _jsx(Badge, { bg: "primary", className: "ms-1 pill-round px-2", pill: true, children: _jsxs("span", { className: "text-decoration-dotted", children: [(Math.round(props.composition.percentage.percentage * 10) / 10).toFixed(1), "%"] }) }) }))] }), _jsx("span", { className: "ms-auto fw-bold d-flex align-items-center", children: _jsx(OverlayTrigger, { placement: "left", overlay: _jsx(Tooltip, { id: 'fee-tooltip-' + props.text, className: "font-default", children: props.fee.amountInDstToken == null ? (_jsxs("span", { className: "ms-auto d-flex align-items-center", children: [_jsx(TokenIcon, { tokenOrTicker: props.fee.amountInSrcToken.token, className: "currency-icon-small", style: { marginTop: '-2px' } }), _jsxs("span", { children: [props.fee.amountInSrcToken.amount, " ", props.fee.amountInSrcToken.token.ticker] })] })) : (_jsxs("span", { className: "ms-auto text-end", children: [_jsxs("span", { className: "d-flex align-items-center justify-content-start", children: [_jsx(TokenIcon, { tokenOrTicker: props.fee.amountInSrcToken.token, className: "currency-icon-small", style: { marginTop: '-1px' } }), _jsxs("span", { children: [props.fee.amountInSrcToken.amount, " ", props.fee.amountInSrcToken.token.ticker] })] }), _jsx("span", { className: "d-flex align-items-center justify-content-center fw-bold", children: "=" }), _jsxs("span", { className: "d-flex align-items-center justify-content-start", children: [_jsx(TokenIcon, { tokenOrTicker: props.fee.amountInDstToken.token, className: "currency-icon-small" }), _jsxs("span", { children: [props.fee.amountInDstToken.amount, " ", props.fee.amountInDstToken.token.ticker] })] })] })) }), children: _jsx("span", { className: "text-decoration-dotted font-monospace", children: FEConstants.USDollar.format(props.usdValue == null ? 0 : props.usdValue) }) }) })] }));
}
export function GenericFeePanel(props) {
    return (_jsx(_Fragment, { children: _jsx(Accordion, { className: "simple-fee-screen", children: _jsxs(Accordion.Item, { eventKey: "0", className: "tab-accent-nop", children: [_jsxs(Accordion.Header, { className: "font-bigger d-flex flex-row", bsPrefix: "fee-accordion-header", children: [_jsxs("div", { className: "simple-fee-screen__quote", children: [_jsx("div", { className: "sc-text", children: props.isExpired ? (_jsxs("span", { className: "simple-fee-screen__quote__error", children: [_jsx("span", { className: "icon icon-invalid-error" }), _jsx("span", { className: "sc-text", children: "Quote expired" })] })) : !props.outputToken || !props.outputToken ? (_jsx("div", { className: "simple-fee-screen__skeleton" })) : (_jsxs(_Fragment, { children: ["1 ", props.outputToken.ticker, " =", ' ', props.price?.toFixed(props.inputToken.displayDecimals ?? props.inputToken.decimals)
                                                    ?? '-', ' ', props.inputToken.ticker] })) }), _jsx(SwapExpiryProgressCircle, { expired: props.isExpired, timeRemaining: props.remainingTime, totalTime: props.totalTime, show: props.isExpired || (props.totalTime != null && props.remainingTime != null), onRefreshQuote: props.onRefreshQuote })] }), _jsx("div", { className: "icon icon-receipt-fees" }), _jsx("span", { className: "simple-fee-screen__fee", children: props.totalUsdFee == null ? '$0.00' : FEConstants.USDollar.format(props.totalUsdFee) }), _jsx("div", { className: "icon icon-caret-down" })] }), _jsx(Accordion.Body, { className: "simple-fee-screen__body", children: props.fees.map((e, index) => (_jsx(FeePart, { ...e }, index))) })] }) }) }));
}
