/**
 * Generates `src/data/tokenMeta.generated.ts` from the token registry exposed by
 * `src/utils/SwapperFactory.ts`.
 *
 * Run manually with `npx tsx scripts/genTokens.ts`, or automatically via the Vite
 * plugin in `vite.config.ts` (on both `npm start` and `npm run build`).
 */
import * as fs from 'fs';
import * as path from 'path';
import type { Token } from '@atomiqlabs/sdk';
import { fileURLToPath } from 'url';
import { Factory } from '../src/utils/SwapperFactory';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = process.argv[2]
  ? path.resolve(process.cwd(), process.argv[2])
  : path.resolve(__dirname, '../src/data/tokenMeta.generated.ts');

function propertyName(value: string): string {
  return /^[$A-Z_a-z][$\w]*$/.test(value) ? value : JSON.stringify(value);
}

function serializeToken(token: Token): string {
  const properties = Object.entries(token)
    .filter(([key]) => key !== 'equals' && key !== 'toString')
    .map(([key, value]) => `${propertyName(key)}: ${JSON.stringify(value)}`);

  const equalsChecks = [
    `other.chainId === ${JSON.stringify(token.chainId)}`,
    `other.ticker === ${JSON.stringify(token.ticker)}`,
  ];
  if (token.chain === 'SC') {
    equalsChecks.push(`other.address === ${JSON.stringify(token.address)}`);
  }

  properties.push(`equals: (other: Token) => ${equalsChecks.join(' && ')}`);
  const stringValue = JSON.stringify(token.toString());
  properties.push(`toString: (): ${stringValue} => ${stringValue}`);
  const tokenType =
    token.chain === 'SC'
      ? `SCToken<${JSON.stringify(token.chainId)}>`
      : `BtcToken<${String(token.lightning)}>`;
  return `{ ${properties.join(', ')} } satisfies ${tokenType}`;
}

function main() {
  const tokenGroups = Object.entries(Factory.Tokens);
  const tokenBlocks = tokenGroups.map(([chainId, tokens]) => {
    const tokenLines = Object.entries(tokens)
      .map(([ticker, token]) => `    ${propertyName(ticker)}: ${serializeToken(token)},`)
      .join('\n');
    return `  ${propertyName(chainId)}: {\n${tokenLines}\n  },`;
  });

  const resolverLines = Object.keys(Factory.TokenResolver)
    .map((chainId) => `  ${propertyName(chainId)}: createTokenResolver(Tokens.${propertyName(chainId)}),`)
    .join('\n');

  const output = `// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by \`npx tsx scripts/genTokens.ts\` (also runs automatically via the Vite
// plugin in vite.config.ts). Source of truth: Factory.Tokens and Factory.TokenResolver
// from src/utils/SwapperFactory.ts.

import type { BtcToken, SCToken, Token } from '@atomiqlabs/sdk';

export const Tokens = {
${tokenBlocks.join('\n')}
} satisfies Record<string, Record<string, Token>>;

function createTokenResolver<T extends Record<string, Token>>(tokens: T) {
  const tokensByAddress = new Map<string, T[keyof T]>();
  for (const ticker in tokens) {
    const token = tokens[ticker];
    tokensByAddress.set(token.address, token);
  }

  return {
    getToken: (address: string) => tokensByAddress.get(address),
  };
}

export const TokenResolver = {
${resolverLines}
};
`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, output);
  console.log(`[genTokens] wrote ${path.relative(process.cwd(), OUT_PATH)}`);
}

main();
